flake, nix: update `nixos-tests` to `nixos-26.05`
- flake, nix: update `nixpkgs` to `nixos-26.05`:
  Fix an error that appeared after updating:
  https://applicative.systems/nixos-test-driver-manual/changelog/#pr-487754-fix-nix-shell-for-driver
- nix: pass `test-helper` via pkgs:
  The updated caused the following error, which was fixed by passing
  `test-helper`via pkgs.
  ```
  error: undefined variable 'test-helper'
  at /.../libvirt/nixos-tests/tests/libvirt-test.nix:43:7:
    42|       pytest
    43|       test-helper
      |       ^
    44|     ];
  ```
- nix: use `QemuMachine` in place of `Machine`:
  https://applicative.systems/nixos-test-driver-manual/changelog/#pr-478109-nspawn-container-backend
- nix: replace deprecated `copy_from_vm` with `copy_from_machine`:
  https://applicative.systems/nixos-test-driver-manual/changelog/#pr-478109-nspawn-container-backend
- nix: set `enableSharedMemory` for numa tests
  With https://github.com/NixOS/nixpkgs/pull/453305, the
  `virtualisation.qemu.enableSharedMemory` option was added, which
  defaults to `true`.
  This sets the `-machine memory-backend` parameter for QEMU.
  The parameter is mutually exclusive with the `-numa memdev` parameter
  that we set for the numa tests.
  To fix the tests, we set
  `virtualisation.qemu.enableSharedMemory = false`.

On-behalf-of: SAP julian.schindel@sap.com
Signed-off-by: Julian Schindel <julian.schindel@cyberus-technology.de>